### PR TITLE
Basaltic fix

### LINKED ISSUE #65: Dev: Split basaltic traps into its own spell
Separate it from bomb so that it can get individual damage bonus from patient hunter

also will generalize some spell merge code in the meantime

### PR DESCRIPTION
**Pull request by hppeng-wynn**
Fix #65

### CODE REVIEW

File: js/atree_constants.js [hunk 1]
```diff
@@ -341,7 +341,6 @@ const atrees = {
             "desc": "When you hit the ground with Arrow Bomb, leave a Trap that damages enemies. (Max 2 Traps)",
             "archetype": "Trapper",
             "archetype_req": 2, 
-            "base_abil": "Arrow Bomb",
```
Comment (ferricles) [inline js/atree_constants.js:344]: what

Comment (ferricles) [reply js/atree_constants.js:344]: nvm i see what's happening here

**Review by ferricles — APPROVED** [review]
